from binance.client import Client

# constants.py

ACTION_BUY = Client.SIDE_BUY
ACTION_SELL = Client.SIDE_SELL
ORDER_TYPE_MARKET = Client.ORDER_TYPE_MARKET
ORDER_TYPE_LIMIT = Client.ORDER_TYPE_LIMIT
ORDER_STATUS_EXPIRED = Client.ORDER_STATUS_EXPIRED
ORDER_STATUS_FILLED = Client.ORDER_STATUS_FILLED
ORDER_STATUS_NEW = Client.ORDER_STATUS_NEW
